Andrewthe13th/Inventory_Kamera

GenshinGuide/GOOD.cs, GenshinGuide/Scraper.cs, GenshinGuide/tessdata/.gitmodules
Fixes #46 by adding Thoma in the scraper and the GOOD format.
=> Add Thoma to the scraper and GOOD.

InventoryKamera/Scraper.cs
Apologies for the trailing whitespace/formatting changes that's automated with my VS setup, but this basically adds Thoma back into Scraper.cs
Tested in game.
=> fix: thoma was missing in Scraper.cs

README.md
This README change will greatly improve instructions for all non-geek Genshin Impact users, that would like to enjoy managing their artifacts and inventory.
As a thanks to #53
=> Update README with multiple requirements

InventoryKamera/Artifact.cs, InventoryKamera/Character.cs, InventoryKamera/InventoryKamera.cs, InventoryKamera/UserInterface.cs, InventoryKamera/Weapon.cs
Weapon and Artifact cards now displayed regardless if they are saved or not.
Added basic logging for weapon and artifact card images to filesystem. Currently only adds so manual user-end clearing necessary for now.
=>  Crash mitigation and additional debugging/error reporting information

InventoryKamera/App.config, InventoryKamera/Artifact.cs, InventoryKamera/ArtifactScraper.cs, InventoryKamera/Form1.Designer.cs, InventoryKamera/Form1.cs, InventoryKamera/InventoryKamera.cs, InventoryKamera/Properties/Settings.Designer.cs, InventoryKamera/Properties/Settings.settings, InventoryKamera/UserInterface.cs, InventoryKamera/Weapon.cs, InventoryKamera/WeaponScraper.cs
Scan settings now accessed at runtime.
Weapon and Artifacts previewed before result is shown.
Fixed accidental inverted validation for weapons and artifacts.
=> Added rarity filters for weapons and artifacts

README.md
This PR improves readability in the README file, including grammar and misspelling errors.
Also changes miHoYo to HoYoverse and Cognosphere Pte. Ltd.
=> Updates README for up-to-date info

InventoryKamera/App.config, InventoryKamera/InventoryKamera.csproj, InventoryKamera/Program.cs, InventoryKamera/Properties/AssemblyInfo.cs, InventoryKamera/Properties/Settings.Designer.cs, InventoryKamera/Properties/Settings.settings, InventoryKamera/data/DatabaseManager.cs, InventoryKamera/data/GOOD.cs, InventoryKamera/data/InventoryKamera.cs, InventoryKamera/game/Navigation.cs, InventoryKamera/packages.config, InventoryKamera/scraping/ArtifactScraper.cs, InventoryKamera/scraping/CharacterScraper.cs, InventoryKamera/scraping/MaterialScraper.cs, InventoryKamera/scraping/Scraper.cs, InventoryKamera/scraping/WeaponScraper.cs, InventoryKamera/ui/UserInterface.cs, InventoryKamera/ui/databaseupdater/DatabaseUpdateForm.cs, InventoryKamera/ui/main/MainForm.Designer.cs, InventoryKamera/ui/main/MainForm.cs, InventoryKamera/ui/main/MainForm.resx
New:
* Update alert popup for keeping up with game release versions. 
* Limits to one automatic check per hour to avoid going over GitHub's API limit. Using the updater with `Create New Lists` enabled forces the API call and resets the one hour timer for automatic checking.
* File logging and archiving. Keeps the last run log + 4 additional log archives. Uses [NLog](https://nlog-project.org/)
* Added full item card to logging
=> Automatic Updating and Logging

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md
This will make sure developers receives sufficient information about what happened, in a single, unified form.
=> Create Issue Templates

InventoryKamera/data/DatabaseManager.cs
=> Fixed artifacts not being correctly updated

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement-request.md, .github/ISSUE_TEMPLATE/fallback_template.md, .github/ISSUE_TEMPLATE/feature-request.md
* Hide instruction lines in bug-report.md
* Hide instruction lines in enhancement-request.md
* Hide instruction lines in fallback_template.md
* Update enhancement-request.md
* Update feature-request.md
* Update fallback_template.md
* Update enhancement-request.md
=> Hides instruction lines on Markdown preview

README.md
There are some invalid links that led to users not applying the Issue Template. It has been fixed.
Although, this PR DOES NOT supersede #296 .
=> [HOTFIX] Fix invalid links in README

InventoryKamera/data/DatabaseManager.cs
WebClient not downloading file as utf8 in other country.
Change encoding to utf8 solve the update problem.
=> Fixing update fail

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/fallback_template.yml
This PR is a future-proof fix for bug reports on game and scanner versions. 
This PR also includes changes to the availability of Discussions.
=> Better support for new version + bug reporters

InventoryKamera/game/Navigation.cs, InventoryKamera/scraping/CharacterScraper.cs
Requires a full party to work properly (4 Characters).
=> Fixes the Tartaglia passive fix.

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/fallback_template.yml, README.md
Courtesy of #342 and @mineminemine, this PR is fixed and ready to merge.
=> Fix typos according to #342

InventoryKamera/ui/UserInterface.cs
Some threads uses old parsed value so artifact count become incorrect
Issue #304
=> Fix incorrect count

InventoryKamera/game/Navigation.cs
Works correctly for me, but it's required confirmation from others.
Issue #329
=> Fullscreen focus support

InventoryKamera/ui/main/MainForm.cs
Adding this for #353 and based off PR #354.
See `MainForm_Activate()`. Can be tested by doing a scan and either letting it finish or aborting it.
Also, I'm not sure why there wasn't proper indentation for the file; it was a mess previously, so it appears to be a lot of changes when there are only a few lines added.
=> Bring window to front once the scan is finished or stopped

InventoryKamera/scraping/MaterialScraper.cs
=> Fixed #372

README.md
https://en.wikipedia.org/wiki/2K_resolution
https://en.wikipedia.org/wiki/Graphics_display_resolution#2560_%C3%97_1440_(QHD)
=> Use correct term for 1440p resolution
